Create HexNode.java
djimenezmsu/Hex pull request #3
Opened 2023-04-19 10:23 UTC by jaycoug

2023-04-19 22:38 UTC, dwilliams56 approved these changes

2023-04-19 23:11 UTC, djimenezmsu commented on src/main/Boards/HexNode.java
> +	}
If value represents the color of the player (1, 2) why should the constructor without a value passed set the value to 0 (not a valid color)? As a group we should decide if the default color of the player should be red or blue in my opinion. Setting it to default as 0 doesn't make sense to me.

2023-04-19 23:11 UTC, djimenezmsu requested changes
See above comment

2023-04-19 23:33 UTC, srichardson22 approved these changes

2023-04-20 12:59 UTC, jaycoug commented on src/main/Boards/HexNode.java
> +	}
This constructor follows the Trevorah project's constructor in the HexLocation class for setting the node ID without inputting a value for the player. (Setting a specific player is handled in the constructor below this one.) The 0 comes from the Board.BLANK value in the Board interface (which I didn't use, but we can if we want.) I think setting the value to 0 just indicates that the tile hasn't been selected by a player, and sets the color/status to white/unselected. This looks to be important for when the board is initialized with unselected tiles in the initBoard() method of the BoardData class. We can try it without, though, if it still seems extraneous.

2023-04-20 13:00 UTC, djimenezmsu commented on src/main/Boards/HexNode.java
> +	}
Ok, thanks for the explanation

2023-04-20 13:00 UTC, djimenezmsu approved these changes

2023-04-20 13:00 UTC, merged