Create AdjMatrix.java
djimenezmsu/Hex pull request #4
Opened 2023-04-19 10:28 UTC by jaycoug

2023-04-19 22:38 UTC, dwilliams56 approved these changes

2023-04-19 23:14 UTC, djimenezmsu commented on src/main/Boards/AdjMatrix.java
> +	  }
Just a suggestion, but for debugging purposes, I think we should throw an invalid operation exception with a message referencing where the exception came from. That way, if we run into a null reference exception somewhere leading here, we'll be able to quickly diagnose the issue.

2023-04-19 23:18 UTC, djimenezmsu commented on src/main/Boards/AdjMatrix.java
> +	  }
For type safety, we should use Integer.tryParse(data.get(x, y)) and wrap it in a try catch. In the catch we should throw the exception up with a message about where it came from.

2023-04-19 23:19 UTC, djimenezmsu requested changes
see above

2023-04-19 23:32 UTC, srichardson22 approved these changes

2023-04-20 18:50 UTC, djimenezmsu approved these changes
I've went it and just added the exception thrown with a message of where it came from. I tried adding a safer type casting of the read method but I couldn't figure out a way that wasn't worse than it is. Let me know if this is okay

2023-04-21 11:25 UTC, merged